### ISSUE TITLE
Players who are dead at the start of a game will become stuck

### ISSUE THREAD

**Issue by zedwick** [xaniox/HeavySpleef#17]
If a player has joined a queue or lobby for a game, and is subsequently killed and does not respawn in time before the game starts they will become stuck in place, glitching-out and invisible to other players, where they died upon attempting to respawn, holding a spleef shovel. When the game ends they will be freed, but still retain their spleef shovel (and presumably never get their inventory back, though I do not use this feature).

To reproduce:
1. join a spleef queue for a game in-session
2. be killed
3. wait until new spleef game starts, and am holding a shovel
4. respawn, be stuck
5. when game ends become unstuck and beat all other players in game lobby with your super spleef shovel

**Comment by xaniox** [comment]
This and your other two issues should have been fixed by build #278 available [here](https://ci.xaniox.de/job/HeavySpleef/). 

It would be nice if you could verify that these fixes are working for you :)

**Comment by zedwick** [comment]
Ah wow, didn't expect fixes so soon. Thanks! I'll try to test these with some players tonight.

**Comment by zedwick** [comment]
![screen shot 2016-03-26 at 22 11 53](https://cloud.githubusercontent.com/assets/991130/14062675/d26a93b4-f39f-11e5-841e-9df2228c8894.png)
I got killed whilst in a queue, and players started jittering about popping in about my screen every second ish until the game started pre-game countdown, when the player entities start duplicating into the thousands locking up my client. The above is all I can see, but cannot do anything.
![screen shot 2016-03-26 at 22 04 36](https://cloud.githubusercontent.com/assets/991130/14062683/2cf1bfc4-f3a0-11e5-9b36-df7965f7f72a.png)
There's an example of entity count from an earlier attempt, as far as I can tell that's all players (there's 12 players online). It jumped from 706 to that in one frame, which took a couple of minutes to appear - client very dead.

By the other player's chat in the console, it seems I was in the game and the game could not end because I was in it and invisible. No-one else seemed to suffer any rendering issue like I did.

**Comment by xaniox** [comment]
Please check out build #279. It seems like I forgot to change the player death event's scope to be global. A player that is queued for a game will now automatically leave the queue on death.

**Comment by zedwick** [comment]
That does remove me from the queue, thanks.

I still have the rendering issues which near-freezes my client when the countdown starts when dead. Unsure if that's exactly HeavySpleef's fault, though...

**Comment by xaniox** [comment]
Normally you shouldn't be able to stay in the game when you die. If you die while in lobby you should get kicked out of the game and the queue case has also been fixed. I see no way how you would be able to achieve being dead and in-game while the game is starting...

**Comment by zedwick** [comment]
I don't mean I have the rendering issue when i am in the game, just being near the arena whilst dead causes the players to start duplicating when the countdown starts. I am using spleef in a dedicated server for the spleef game, so I have players not associated with a game, inqueue and in lobby all in the same 'lobby' area, which is what you see in the first image. So players are always near the arena in my case.

**Comment by xaniox** [comment]
Hm, that sounds like a very strange bug to me. Would it be possible to try that out directly on your server?

**Comment by zedwick** [comment]
Sure, would you be around in an hour?

**Comment by xaniox** [comment]
Yes, I will try to be online then.

**Comment by zedwick** [comment]
Server address is: latest.zedwork.co.uk
